object Dependencies {

        const val coreKtx = "androidx.core:core-ktx:1.7.0"
        const val appCompat = "androidx.appcompat:appcompat:1.6.1"
        const val material = "com.google.android.material:material:1.8.0"
        const val constraint = "androidx.constraintlayout:constraintlayout:2.1.4"
        const val retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
        const val okhttp = "com.squareup.okhttp3:okhttp:4.10.0"
        const val logging = "com.squareup.okhttp3:logging-interceptor:4.7.2"
        const val daggerHilt = "com.google.dagger:hilt-android:2.45"
        const val gsonConverter = "com.squareup.retrofit2:converter-gson:2.9.0"
        const val kaptHiltAndroid = "com.google.dagger:hilt-android-compiler:2.45"
        const val kaptHiltCompiler = "androidx.hilt:hilt-compiler:1.0.0-alpha03"
        const val junit = "junit:junit:4.13.2"
        const val espresso = "androidx.test.espresso:espresso-core:3.5.1"
        const val navigationFragmentKtx = "androidx.navigation:navigation-fragment-ktx:2.5.3"
        const val navigationUiKtx = "androidx.navigation:navigation-ui-ktx:2.5.3"
        const val mockWebServer = "com.squareup.okhttp3:mockwebserver:4.9.1"
        const val gson = "com.google.code.gson:gson:2.8.6"
        const val uiAutomator = "androidx.test.uiautomator:uiautomator:2.2.0"
        const val archCoreTesting = "android.arch.core:core-testing:1.1.1"
}